[project]
name = "catalog-service"
version = "0.1.0"
description = "catalog service written in python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "pydantic>=2.12.5",
    "uvicorn>=0.40.0",
]
